[package]
name = "akd-keytrasparency"
version = "0.1.0"
edition = "2021"

[dependencies]
akd = { version = "0.12.0-pre.8", features = ["whatsapp_v1"] }
tokio = { version = "1", features = ["full"] }
hex = "0.4"
sha2 = "0.10.8"  # Per convertire i dati binari in formato esadecimale
sha256 = "1.5.0"